"""empty message

Revision ID: e7a69ba13999
Revises: b6702c6eb82f
Create Date: 2023-12-18 15:11:08.156527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a69ba13999'
down_revision = 'b6702c6eb82f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('email', type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
    # op.add_column('x_user_token', sa.Column('x_receiver_id', sa.Integer(), nullable=False))
    # op.add_column('x_user_token', sa.Column('x_receiver_id', sa.Integer(), nullable=False, server_default=DefaultClause("0")))
